= Red Hat Insights API
:experimental: true
:product-name:

Red Hat Insights allows you to investigate and make changes to the configuration of hosts managed by Red Hat through REST APIs. This cheat sheet covers the basic APIs. All examples are performed on https://console.redhat.com/api/[https://console.redhat.com/api/]. Refer to https://console.redhat.com/docs/api[https://console.redhat.com/docs/api] for the latest API specifications and deprecations.

== Authentication

The Insights API provides secure REST services over HTTPS endpoints. This protects authentication credentials in transit.

=== Red Hat token-based authentication via service account (recommended)

. Create a new service account on the https://console.redhat.com/iam/service-accounts[Red Hat Hybrid Cloud Console].
. Obtain service account credentials (Client ID and Client Secret).
. Add the service account to the applicable https://console.redhat.com/iam/user-access/groups[User Access Groups] (service accounts *do not* inherit permissions from Default access groups, so they must be granted access permissions by placing them in a User Group).
. Generate an access token using Red Hat's single sign-on (SSO) technology using the service account credentials <client_id> and <client_secret>:
+
----
curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token -d "grant_type=client_credentials" -d "scope=api.console" -d client_id=<client_id> -d client_secret=<client_secret> 
----
. Red Hat's SSO will respond with a JSON object containing an access token. This access token can be used to make authenticated requests to APIs by including the access_token generated in the previous step in an `Authorization: Bearer` HTTP header in your request:
+
----
Authorization: Bearer <access_token>
----

=== Red Hat API token authentication

. Log in to the https://access.redhat.com/[Red Hat Customer Portal] with your username and password.
. Generate an offline token using https://access.redhat.com/management/api[Red Hat API Tokens] by following the instructions.
. Generate an access token, submitting the offline token generated in the previous step:
+
----
curl https://sso.redhat.com/auth/realms/redhat-external/protocol/openid-connect/token -d grant_type=refresh_token -d client_id=rhsm-api -d refresh_token=<offline_token>
----
. Include the access token generated in the previous step in an `Authorization: Bearer` HTTP header in your request:
+
----
Authorization: Bearer <access_token>
----

Additional information about Red Hat API Token authentication can be found in the https://access.redhat.com/articles/3626371[Getting started with Red Hat APIs] KB article.

=== Basic authentication (deprecated)

*Important:* Basic authentication is now deprecated. Red Hat does not support basic authorization to connect to services' APIs. Token-based authentication is recommended. More information about transitioning from basic authentication to token-based authentication via service accounts is described on the https://access.redhat.com/articles/7036194[Red Hat Customer Portal].


== Common activities

=== Host inventory

Get all hosts in the account:
----
GET /inventory/v1/hosts
----

NOTE: Filtering by staleness satus ensures that only relevant systems are queried (e.g., `&staleness=fresh` or `&staleness=stale`)

Get system details (e.g., after registration, using the UUID provided):
----
GET /inventory/v1/hosts/<uuid>
----

Get all facts from a system' system profile:
----
GET /inventory/v1/hosts/<uuid>/system_profile
----

NOTE: Optimize queries by specifying only the required facts using the `fields` parameter (e.g., `?fields[system_profile]=arch&fields[system_profile]=cpu_model&fields[system_profile]=os_release`)

Get hosts and retrieve system profile fields in one request:
----
GET /inventory/v1/hosts?fields[system_profile]=arch,os_release,number_of_cpus
----

Get a system’s tags:
----
GET /inventory/v1/hosts/<uuid>/tags
----

Get a subset of systems (using a filter on system profile):
----
GET /inventory/v1/hosts?filter[system_profile][infrastructure_type]=virtual
----
or
----
GET /inventory/v1/hosts?filter[system_profile][operating_system][RHEL][version][eq]=8.5
----

Remove a system from inventory:
----
DELETE /inventory/v1/hosts/<uuid>
----

=== Export inventory

Initiate an export request:
----
POST /export/v1/exports
{
  "name": "Inventory Export",
  "format": "csv",
  "sources": [
    {
      "application": "urn:redhat:application:inventory", 
      "resource": "urn:redhat:application:inventory:export:systems"
    }  
  ] 
}
----

Retrieve export status request:
----
GET /exports/<export_id>/status
----

Download the generated export (as a zip file):
----
GET /exports/<export_id>
----

=== Image Builder

Submit a new compose image request
----
POST /image-builder/v1/compose
{
  "image_name": "My latest RHEL9 guest image",
  "distribution": "rhel-95",
  "image_requests": [
    {
      "architecture": "x86_64",
      "image_type": "guest-image",
      "upload_request": {
        "type": "aws.s3",
        "options": {}
      }
    }
  ]
}
----

Get a list of compose image request IDs:
----
GET /image-builder/v1/composes/
----

Get the status of a compose image request
----
GET /image-builder/v1/composes/<compose_id>
----

Related blog post on https://www.redhat.com/en/blog/using-hosted-image-builder-its-api[Using hosted image builder via its API].

=== Repositories and Content Templates

This section documents the `content-sources` endpoint for managing repositories and content templates in Red Hat Insights.

*Managing repositories*

Get a list of all existing repositories:
----
GET /content-sources/v1.0/repositories/
----

Create a new custom repository:
----
POST /content-sources/v1.0/repositories/
{
  "distribution_arch": "x86_64",
  "distribution_versions": ["10"],
  "gpg_key": "-----BEGIN PGP PUBLIC KEY BLOCK-----\n\...\n-----END PGP PUBLIC KEY BLOCK-----",
  "metadata_verification": false,
  "module_hotfixes": false,
  "name": "EPEL 10 Everything x86_64",
  "snapshot": false,
  "url": "https://dl.fedoraproject.org/pub/epel/10/Everything/x86_64/"
}
----
NOTE: to create multiple repositories at once, use the bulk API: `POST /content-sources/v1.0/repositories/bulk_create/`

*Managing content templates*

Create a new content template
```
POST /content-sources/v1.0/templates/
{
  "arch": "x86_64",
  "description": "",
  "name": "My RHEL10 template",
  "repository_uuids": [
        "<repository1 id>",
        "<repository2 id>",
        "<repository3 id>"
  ],
  "use_latest": true,
  "version": "10"
}
```

*Assigning systems to a content template*

- *For system on RHEL 9.6 or RHEL 10 and later:*
You can assign the template at registration time:
```
rhc connect --content-template=<template_name>
```
NOTE: Assigning a system to a template will overwrite any previously assigned template.
NOTE: This method avoids the need to run `subscription-manager` separately.

- *For systems before RHEL 9.6 and RHEL 10:*
You can assign the template using the `patch` API:
```
PUT /patch/v3/templates/<template id>/systems
{
  "systems": [
    "<system1 uuid>",
    "<system2 uuid>"
  ]
}
```
NOTE: Assigning a system to a template will overwrite any previously assigned template.
The system will pick up content from your assigned content template when refreshing `subscription-manager`:
```
rhc connect
subscription-manager refresh
```

- *For all systems (without using rhc):*
Alternatively, manually download the `config.repo` repository file for your system configuration:
```
curl -o /etc/yum.repos.d/template.repo  https://cert.console.redhat.com/api/content-sources/v1/templates/<template id>/config.repo
```
NOTE: Systems consuming a template in this manner will not properly report applicable errata within Insights. The previous methods with `rhc` and `subscription-manager` are recommended.

*Updating system content*

To apply the latest content updates from the template, run: `dnf update`

=== Advisor

Get all active hits for the account:
----
GET /insights/v1/rule/
----

Get all rule hits on hosts:
----
GET /insights/v1/export/hits/
----

NOTE: Exports are available as CSV and JSON.

Get all active hits with Ansible remediation playbooks:
----
GET /insights/v1/export/hits?has_playbook=true
----

Get summary of all hits for a given system :
----
GET /insights/v1/system/<uuid>
----

=== Vulnerabilities

Get vulnerabilities affecting systems in the account:
----
GET /vulnerability/v1/vulnerabilities/cves?affecting=true
----

Get executive reports, e.g., CVEs by severity, top CVEs, etc.:
----
GET /vulnerability/v1/report/executive
----

=== Compliance
Get a list of Security Content Automation Protocol (SCAP) policies
----
GET /compliance/v2/policies
----

Get systems associated with Security Content Automation Protocol (SCAP) policies:
----
GET /compliance/v2/systems&filter=assigned_or_scanned=true
----

Associate a system to a Security Content Automation Protocol (SCAP) policy:
----
PATCH /compliance/v2/policies/<policy_id>/systems/<system_id>
----

Retrieve a list of all available compliance reports:
----
GET /compliance/v2/reports
----

Retrieve a list of affected hosts for a compliance report:
----
GET /compliance/v2/reports/<report_id>/test_results
----

=== Policies

Get all defined policies:
----
GET /policies/v1/policies
----

Create a new policy:
----
POST /policies/v1/policies
{
  "name": "my_policy",
  "description": "My policy",
  "isEnabled": true,
  "conditions": "arch = \"x86_64\"",
  "actions": "notification"
}
----

NOTE: `DELETE` and `PUT` operations are also available on `/policies/<policy_id>`.

Get all systems triggering a policy:
----
GET /policies/v1/policies/<policy_id>/history/trigger
----

=== Patches

Get all applicable advisories for my systems (patches available):
----
GET /patch/v3/export/advisories
----

=== Subscriptions

Get all systems with a matching RHEL for x86 subscription:
----
GET /rhsm-subscriptions/v1/instances/products/RHEL%20for%20x86
----

=== Export Subscriptions

Initiate an export request:
----
POST /export/v1/exports
{
  "name": "Subscriptions Export",
  "format": "csv",
  "sources": [
    {
      "application": "subscriptions", 
      "resource": "subscriptions"
    }  
  ] 
}
----

Retrieve export status request:
----
GET /exports/<export_id>/status
----

Download the generated export (as a zip file):
----
GET /exports/<export_id>
----

=== Remediations

Get a list of defined remediations:
----
GET /remediations/v1/remediations
----

Create a new remediation and assign systems:
----
POST /remediations/v1/remediations
{
  "name": "Fix Critical CVEs",
  "archived": true,
  "auto_reboot": true,
  "add": {
    "issues": [
      {
        "id": "advisor:CVE_2017_6074_kernel|KERNEL_CVE_2017_6074",
        "resolution": "mitigate",
        "systems": [
          "<uuid>"
        ]
      }
    ]
  }
}
----

NOTE: DELETE and PATCH operations are also available on `/remediations/v1/remediations/<remediation_id>`.

Get an Ansible remediation playbook:
----
GET /remediations/v1/remediations/<remediation_id>/playbook
----

Execute a remediation:
----
POST /remediations/v1/remediations/<remediation_id>/playbook_runs
----

=== Integrations and notifications

Get event log history for a list of last triggered Insights events and actions:
----
GET /notifications/v1/notifications/events?endDate=2021-11-23&limit=20&offset=0&sortBy=created%3ADESC&startDate=2021-11-09
----

Get list of configured third party integrations:
----
GET /integrations/v1/endpoints
----

== Python examples

The following Python code interacts with the Insights API using the `requests` library to abstract away the complexity of handling HTTP requests.

----
$ python -m pip install requests
----

=== Authentication

----
>>> headers = {'Authorization': 'Bearer <access_token>'}
----

=== GET

----
>>> import requests
>>> insights_api_url = "https://console.redhat.com/api/inventory/v1/hosts"
>>> response = requests.get(insights_api_url, headers=headers)
>>> response.status_code
200
>>> response.json()
{'total': 1195, 'count': 50, 'page': 1, 'per_page': 50, 'results': [{'insights_id': '<uuid>', [...]
----

=== POST

----
>>> import requests
>>> insights_api_url = "https://console.redhat.com/api/policies/v1/policies?alsoStore=True"
>>> policy = {"name": "my_policy", "description": "My policy", "isEnabled": True, "conditions": "arch = \"x86_64\"", "actions": "notification"}
>>> response = requests.post(insights_api_url, headers=headers, json=policy)
>>> response.status_code
201
>>> response.json()
{'id': '<policy_id>', 'name': 'my_policy', 'description': 'My policy', 'isEnabled': True, 'conditions': 'arch = "x86_64"', 'actions': 'notification', 'mtime': '2024-10-17 15:23:02.942', 'ctime': '2024-10-17 15:23:02.942', 'lastTriggered': 0}
----

== Ansible example

The following Ansible playbook uses the `ansible.builtin.uri` module to interact with the Insights API.

----
---
- hosts: localhost
  connection: local
  gather_facts: no

  vars:
    insights_api_url: "https://console.redhat.com/api"
    insights_auth: "Bearer <access_token>"

  tasks:
  - name: Get Inventory
    uri:
      url: "{{ insights_api_url }}/inventory/v1/hosts/"
      method: GET
      return_content: yes
      headers:
         Authorization: "{{ insights_auth }}"
      status_code: 200
   register: result

  - name: Display inventory
    debug:
      var: result.json
----

== Additional Resources

* https://docs.redhat.com/en/documentation/red_hat_insights/1-latest/html/using_the_red_hat_insights_api/index[Using the Red Hat Insights API] – Comprehensive documentation on authentication, endpoints, and usage of the Insights API.
